/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as PlantsRouteImport } from './routes/plants'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as MobileIndexRouteImport } from './routes/mobile.index'
import { Route as MobileLocationsRouteImport } from './routes/mobile.locations'
import { Route as MobileNewPlantRouteImport } from './routes/mobile.new-plant'
import { Route as MobilePlantsRouteImport } from './routes/mobile.plants'
import { Route as MobileSettingsRouteImport } from './routes/mobile.settings'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects_.$projectId'
import { Route as ClientsClientIdReportRouteImport } from './routes/clients_.$clientId.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsRoute = PlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MobileRoute,
} as any)
const MobileLocationsRoute = MobileLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => MobileRoute,
} as any)
const MobileNewPlantRoute = MobileNewPlantRouteImport.update({
  id: '/new-plant',
  path: '/new-plant',
  getParentRoute: () => MobileRoute,
} as any)
const MobilePlantsRoute = MobilePlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => MobileRoute,
} as any)
const MobileSettingsRoute = MobileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MobileRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdReportRoute = ClientsClientIdReportRouteImport.update({
  id: '/clients_/$clientId/report',
  path: '/clients/$clientId/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/mobile': typeof MobileRouteWithChildren
  '/plants': typeof PlantsRoute
  '/projects': typeof ProjectsRoute
  '/schedule': typeof ScheduleRoute
  '/workers': typeof WorkersRoute
  '/mobile/locations': typeof MobileLocationsRoute
  '/mobile/new-plant': typeof MobileNewPlantRoute
  '/mobile/plants': typeof MobilePlantsRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/mobile/': typeof MobileIndexRoute
  '/clients/$clientId/report': typeof ClientsClientIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/plants': typeof PlantsRoute
  '/projects': typeof ProjectsRoute
  '/schedule': typeof ScheduleRoute
  '/workers': typeof WorkersRoute
  '/mobile/locations': typeof MobileLocationsRoute
  '/mobile/new-plant': typeof MobileNewPlantRoute
  '/mobile/plants': typeof MobilePlantsRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/mobile': typeof MobileIndexRoute
  '/clients/$clientId/report': typeof ClientsClientIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/mobile': typeof MobileRouteWithChildren
  '/plants': typeof PlantsRoute
  '/projects': typeof ProjectsRoute
  '/schedule': typeof ScheduleRoute
  '/workers': typeof WorkersRoute
  '/mobile/locations': typeof MobileLocationsRoute
  '/mobile/new-plant': typeof MobileNewPlantRoute
  '/mobile/plants': typeof MobilePlantsRoute
  '/mobile/settings': typeof MobileSettingsRoute
  '/projects_/$projectId': typeof ProjectsProjectIdRoute
  '/mobile/': typeof MobileIndexRoute
  '/clients_/$clientId/report': typeof ClientsClientIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/mobile'
    | '/plants'
    | '/projects'
    | '/schedule'
    | '/workers'
    | '/mobile/locations'
    | '/mobile/new-plant'
    | '/mobile/plants'
    | '/mobile/settings'
    | '/projects/$projectId'
    | '/mobile/'
    | '/clients/$clientId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/plants'
    | '/projects'
    | '/schedule'
    | '/workers'
    | '/mobile/locations'
    | '/mobile/new-plant'
    | '/mobile/plants'
    | '/mobile/settings'
    | '/projects/$projectId'
    | '/mobile'
    | '/clients/$clientId/report'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/mobile'
    | '/plants'
    | '/projects'
    | '/schedule'
    | '/workers'
    | '/mobile/locations'
    | '/mobile/new-plant'
    | '/mobile/plants'
    | '/mobile/settings'
    | '/projects_/$projectId'
    | '/mobile/'
    | '/clients_/$clientId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  MobileRoute: typeof MobileRouteWithChildren
  PlantsRoute: typeof PlantsRoute
  ProjectsRoute: typeof ProjectsRoute
  ScheduleRoute: typeof ScheduleRoute
  WorkersRoute: typeof WorkersRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ClientsClientIdReportRoute: typeof ClientsClientIdReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants': {
      id: '/plants'
      path: '/plants'
      fullPath: '/plants'
      preLoaderRoute: typeof PlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/locations': {
      id: '/mobile/locations'
      path: '/locations'
      fullPath: '/mobile/locations'
      preLoaderRoute: typeof MobileLocationsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/new-plant': {
      id: '/mobile/new-plant'
      path: '/new-plant'
      fullPath: '/mobile/new-plant'
      preLoaderRoute: typeof MobileNewPlantRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/plants': {
      id: '/mobile/plants'
      path: '/plants'
      fullPath: '/mobile/plants'
      preLoaderRoute: typeof MobilePlantsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/settings': {
      id: '/mobile/settings'
      path: '/settings'
      fullPath: '/mobile/settings'
      preLoaderRoute: typeof MobileSettingsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/projects_/$projectId': {
      id: '/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients_/$clientId/report': {
      id: '/clients_/$clientId/report'
      path: '/clients/$clientId/report'
      fullPath: '/clients/$clientId/report'
      preLoaderRoute: typeof ClientsClientIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MobileRouteChildren {
  MobileLocationsRoute: typeof MobileLocationsRoute
  MobileNewPlantRoute: typeof MobileNewPlantRoute
  MobilePlantsRoute: typeof MobilePlantsRoute
  MobileSettingsRoute: typeof MobileSettingsRoute
  MobileIndexRoute: typeof MobileIndexRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileLocationsRoute: MobileLocationsRoute,
  MobileNewPlantRoute: MobileNewPlantRoute,
  MobilePlantsRoute: MobilePlantsRoute,
  MobileSettingsRoute: MobileSettingsRoute,
  MobileIndexRoute: MobileIndexRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  MobileRoute: MobileRouteWithChildren,
  PlantsRoute: PlantsRoute,
  ProjectsRoute: ProjectsRoute,
  ScheduleRoute: ScheduleRoute,
  WorkersRoute: WorkersRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ClientsClientIdReportRoute: ClientsClientIdReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
